### ISSUE TITLE
Cannot Re-Edit Downloaded Files

### ISSUE THREAD

**Issue by myepez** [talenfisher/fix3p#55]
# Description
When a user uploads a downloaded file to the application to re-edit, the painting section of the application freezes with the 'Reading Colors...' label near the paintbrush icon.

# Replicating Issue
1. Upload a *new* x3p file
2. Make painting edits to the new file
3. Download the file
4. Drop the *downloaded* file from the local folder location into 'Choose a file or drag one here' section
5. One should be able to see the issue

# Custom Configurations
* Using csafe-mask.xml as the annotation preset setting

**Comment by talenfisher** [comment]
I have identified the cause of the issue and will work on getting a fix in this afternoon.  Sorry for the trouble!

**Comment by talenfisher** [comment]
The fix is now live on https://talenfisher.github.io/fix3p - I'll post again here when the extension has been updated on the chrome web store. If this turns out to not have been fixed for you, please re-open the issue!
